services:
    postgres:
        image: ankane/pgvector:latest
        env_file:
            - .env
        ports:
            - "${DB_PORT}:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
            interval: 10s
            retries: 5

volumes:
    pgdata:
