services:
    postgres:
        image: postgres:15
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "${DB_PORT}:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

    app:
        build: .
        env_file: .env
        command: tail -f /dev/null
        depends_on:
            - postgres

volumes:
    pgdata:
